Repository Twometer/NeonRacer, pull requests merged in 2019-05, with the labels that each got.

#24 Network protocol
  README.md
  build.gradle
  src/main/proto/Entity.proto
  src/main/proto/Login.proto
  src/main/proto/Race.proto
Labels: implementation

#25 Visuals
  src/main/java/neonracer/core/GameContext.java
  src/main/java/neonracer/core/GameContextFactory.java
  src/main/java/neonracer/designer/TrackDesigner.java
  src/main/java/neonracer/gui/GuiManager.java
  src/main/java/neonracer/gui/events/CharInputEvent.java
  src/main/java/neonracer/gui/font/FontRenderer.java
  src/main/java/neonracer/gui/parser/ScreenLoader.java
  src/main/java/neonracer/gui/parser/WidgetFactory.java
  src/main/java/neonracer/gui/screen/CarSelectorScreen.java
  src/main/java/neonracer/gui/screen/ConnectScreen.java
  src/main/java/neonracer/gui/screen/IngameScreen.java
  src/main/java/neonracer/gui/screen/MainScreen.java
  src/main/java/neonracer/gui/screen/Screen.java
  src/main/java/neonracer/gui/util/Animator.java
  src/main/java/neonracer/gui/util/Margin.java
  src/main/java/neonracer/gui/util/PrimitiveRenderer.java
  src/main/java/neonracer/gui/widget/Border.java
  src/main/java/neonracer/gui/widget/Button.java
  src/main/java/neonracer/gui/widget/ImageButton.java
  src/main/java/neonracer/gui/widget/Label.java
  src/main/java/neonracer/gui/widget/ProgressBar.java
  src/main/java/neonracer/gui/widget/TextBox.java
  src/main/java/neonracer/gui/widget/TitleButton.java
  src/main/java/neonracer/gui/widget/base/Widget.java
  src/main/java/neonracer/gui/widget/grid/GridLayoutEngine.java
  src/main/java/neonracer/model/track/Node.java
  src/main/java/neonracer/model/track/Track.java
  src/main/java/neonracer/phys/entity/car/Tire.java
  src/main/java/neonracer/render/GameWindow.java
  src/main/java/neonracer/render/MasterRenderer.java
  src/main/java/neonracer/render/RenderContext.java
  src/main/java/neonracer/render/engine/collider/TrackCollider.java
  src/main/java/neonracer/render/engine/postproc/PostProcessing.java
  src/main/java/neonracer/render/engine/renderers/EntityRenderer.java
  src/main/java/neonracer/render/engine/renderers/TrackRenderer.java
  src/main/java/neonracer/render/gl/GlLoader.java
  src/main/java/neonracer/render/gl/ShaderProvider.java
  src/main/java/neonracer/util/Log.java
  src/main/resources/data/tracks.yml
  src/main/resources/guis/cars.xml
  src/main/resources/guis/connect.xml
  src/main/resources/guis/designer.xml
  src/main/resources/guis/ingame.xml
  src/main/resources/guis/main.xml
  src/main/resources/icon.png
Labels: enhancement, implementation

#31 Track designer fixes
  src/main/java/neonracer/designer/TrackDesigner.java
  src/main/java/neonracer/model/entity/Entity.java
  src/main/resources/data/tracks.yml
  src/main/resources/guis/designer.xml
Labels: enhancement

#34 Track
  src/main/java/neonracer/phys/entity/item/StaticPhysics.java
  src/main/java/neonracer/render/MasterRenderer.java
  src/main/resources/data/cars.yml
  src/main/resources/data/tracks.yml
Labels: implementation
